name: Build and Deploy Zakat Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Get version from package.json
      - name: Get version
        id: version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # Step 5: Run the build script
      - name: Build project
        run: npm run build-standalone

      # Step 6: Verify build output
      - name: Verify build artifacts
        run: |
          ls -R dist/
          [ -f dist/index.html ] || exit 1
          [ -f dist/style.css ] || exit 1
          [ -f dist/app.js ] || exit 1

      # Step 7: Create versioned artifact
      - name: Create versioned artifact
        run: |
          mkdir -p artifacts
          cp -r dist/ artifacts/zakat-calculator-$VERSION/
          zip -r artifacts/zakat-calculator-$VERSION.zip artifacts/zakat-calculator-$VERSION/

      # Step 8: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zakat-calculator-build
          path: |
            artifacts/
            zakat-calculator.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only deploy on main branch

    steps:
      # Step 1: Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: zakat-calculator-build
          path: artifacts

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifacts/zakat-calculator-${{ env.VERSION }}
          keep_files: false