name: Deploy Site
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-minimal
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run clean
      - run: npm run build
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          npm run deploy -- -u "github-actions <github-actions@github.com>"
