name: Deploy Calculator

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-build
          path: dist
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build
          path: dist

      - name: Deploy project
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          # Configure git to use HTTPS with the token
          git remote set-url origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Use GH_TOKEN as environment variable for gh-pages
          GH_TOKEN="${{ secrets.GITHUB_TOKEN }}" npm run deploy -- -m "Deploy Calculator [skip ci]"

      - name: Post-deployment clean-up
        if: always()
        run: |
          echo "Deployment completed."
          rm -rf dist

  report-status:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report deployment status
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "✅ Deployment successful"
            exit 0
          else
            echo "❌ Deployment failed"
            exit 1
          fi